services:
    GepurIt\ActionLoggerBundle\Logger\ActionLoggerInterface:
        class: GepurIt\ActionLoggerBundle\Logger\ActionLogger
        autowire: true

    app.action_logger:
        alias: GepurIt\ActionLoggerBundle\Logger\ActionLoggerInterface
        public: true