services:
    GepurIt\ActionLoggerBundle\Logger\ActionLoggerInterface:
        class: GepurIt\ActionLoggerBundle\Logger\ActionLogger
        autowire: true

    app.action_logger:
        alias: GepurIt\ActionLoggerBundle\Logger\ActionLoggerInterface
        public: true

    GepurIt\ActionLoggerBundle\Repository\:
        resource: '../../Repository'
        autowire: true
        tags: ['doctrine_mongodb.odm.repository_service']